<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CalculatorDemoService1"
     targetNamespace="http://xmlns.oracle.com/SOATestApplication/CalculatorDemoProject/CalculatorDemoService1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/SOATestApplication/CalculatorDemoProject/CalculatorDemoService1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SOAPService">
        <plnk:role name="operations" portType="tns:operations"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/SOATestApplication/CalculatorDemoProject/CalculatorDemoService1"
         location="CalculatorDemoService.wsdl"/>
</wsdl:definitions>
