<wsdl:definitions
     name="DBDataPolling"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GG_DBApplication/GG_DBPollingWriteFile/DBDataPolling"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GG_DBApplication/GG_DBPollingWriteFile/DBDataPolling"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBDataPolling"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DBDataPolling_plt" >
    <plt:role name="DBDataPolling_role" >
      <plt:portType name="tns:DBDataPolling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBDataPolling" schemaLocation="../Schemas/DBDataPolling_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmployeeDetailsCollection_msg">
        <wsdl:part name="EmployeeDetailsCollection" element="top:EmployeeDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBDataPolling_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EmployeeDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
