<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="dbRestPostReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOATestApplication/RestPostDBDemo/dbRestPostReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOATestApplication/RestPostDBDemo/dbRestPostReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbRestPostReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.example.org"
    >
    <plt:partnerLinkType name="dbRestPostReference_plt">
        <plt:role name="dbRestPostReference_role">
            <plt:portType name="tns:dbRestPostReference_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbRestPostReference"
                 schemaLocation="../Schemas/dbRestPostReference_table.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/nxsd_JsonSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="StudentDetailsCollection_msg">
        <wsdl:part name="StudentDetailsCollection" element="top:StudentDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbRestPostReference_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:StudentDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
